name: 'Check if npm package version is changed compared to versio in npm registry'
description: 'Check if npm package version is changed compared to versio in npm registry'
branding:
  icon: 'award'
  color: 'blue'
inputs: {}
outputs:
  is-version-changed:
    description: 'True if version is changed, false otherwise'
    value: ${{ steps.check-is-version-updated.outputs.is-version-changed }}
runs:
  using: 'node16'
  main: 'index.js'
